### ISSUE TITLE
Failure in run with default configuration

### ISSUE THREAD

**Issue by rajneesh2k10** [diniamo/run.nvim#1]
I have setup the plugin with the provided default configuration in wiki. However, the plugin fails to create window when asked to run a command.

I am guessing that the plugin doesn't pass all the required parameters when creating a window to run the command.

Error trace:

```
E5108: Error executing lua: .../.local/share/nvim/lazy/run.nvim/lua/run/terminal.lua:14: bad argument #1 to
'rshift' (number expected, got nil)
stack traceback:
        [C]: in function 'rshift'
        .../.local/share/nvim/lazy/run.nvim/lua/run/terminal.lua:14: in function 'darken'
        .../.local/share/nvim/lazy/run.nvim/lua/run/terminal.lua:86: in function 'prepare'
        .../.local/share/nvim/lazy/run.nvim/lua/run/terminal.lua:97: in function 'run_command'
        .../.local/share/nvim/lazy/run.nvim/lua/run/init.lua:37: in function 'run'
        .../.config/nvim/lua/custom/plugins/run.lua:33: in function </Users/xxx/.config/nvim/lua/custom/plugins/run.lua:30>

```

**Comment by diniamo** [comment]
Hmm, that can only happen if your `Normal` highlight group doesn't have a `bg` color. Do you use a transparent theme?

Note: you don't have to add values you don't want to change to the setup function

**Comment by rajneesh2k10** [comment]
Yes, I do use transparency with my theme.

I guess I need to find what I need to pass to `nvim_open_win` to keep the current theme and have the split?

It would have been wonderful to just have the statusline updated with success(in green)/failure(in red) of the run command if we are only building/running tests. That would just remove the need of having a split window open. In case one needs to find the details, they could toggle a window to view it.

**Comment by diniamo** [comment]
Just disable darkening

**Comment by rajneesh2k10** [comment]
Tried that already. It doesn't help. Is there a default that's set by the plugin?

**Comment by diniamo** [comment]
Yes, as stated by the readme, and as I've told you above. You have to set it to false (also in the readme).

**Comment by diniamo** [comment]
I pushed a fix to check for a bg color as well, so you can also just update.
